// Throwaway-mailbox domains refused at registration. Sourced from the embedded
// game's list so both halves of the deployment agree on what is disposable.
export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  "0-mail.com", "0clickemail.com", "0wnd.net", "0wnd.org", "10mail.com", "10minutemail.co.uk",
  "10minutemail.com", "10minutemail.net", "10minutemail.org", "10minutesmail.fr",
  "1secmail.com", "1secmail.net", "1secmail.org", "20minutemail.com", "30minutemail.com",
  "33m.co", "33mail.com", "33mail.net", "anonbox.net", "anonymbox.com", "antichef.com",
  "antichef.net", "antispam.de", "armyspy.com", "bigstring.com", "binkmail.com", "bobmail.info",
  "boun.cr", "bouncr.com", "bspamfree.org", "bugmenot.com", "burnermail.io", "byom.de",
  "cellurl.com", "chammy.info", "clrmail.com", "cool.fr.nf", "courriel.fr.nf", "cuvox.de",
  "dayrep.com", "dcemail.com", "deadaddress.com", "devnullmail.com", "discard.email",
  "discardmail.com", "discardmail.de", "discardmail.net", "dispostable.com", "dropmail.me",
  "einrot.com", "email-fake.com", "emailfake.com", "emailondeck.com", "emailtemporanea.com",
  "emailtemporanea.net", "esiix.com", "etranquil.com", "etranquil.net", "etranquil.org",
  "fakeinbox.com", "fakemail.fr", "fakemailbox.com", "fakemailgenerator.com",
  "fastmail.fm.disposable", "fivemail.de", "fleckens.hu", "fr.nf", "getairmail.com",
  "getnada.com", "grr.la", "guerrillamail.biz", "guerrillamail.com", "guerrillamail.de",
  "guerrillamail.net", "guerrillamail.org", "guerrillamailblock.com", "gustr.com",
  "guysmail.com", "haltospam.com", "harakirimail.com", "inboxbear.com", "incognitomail.com",
  "incognitomail.org", "instant-mail.de", "jetable.fr.nf", "jourrapide.com", "kasmail.com",
  "killmail.com", "killmail.net", "klzlk.com", "kulturbetrieb.info", "kurzepost.de",
  "laafd.com", "letthemeatspam.com", "lifebyfood.com", "lookugly.com", "lortemail.dk",
  "luxusmail.org", "mail-temporaire.fr", "mailbox52.ga", "mailcatch.com", "mailde.de",
  "mailde.info", "maildrop.cc", "maildrop.cf", "mailexpire.com", "mailforspam.com",
  "mailin8r.com", "mailinator.com", "mailinator.net", "mailinator.org", "mailinator2.com",
  "mailmoat.com", "mailms.com", "mailnesia.com", "mailnull.com", "mailseal.de", "mailtemp.info",
  "mailtemporaire.com", "mailtemporaire.fr", "mailtothis.com", "mailzilla.com", "mailzilla.org",
  "mega.zik.dj", "messagebeamer.de", "mintemail.com", "moakt.cc", "moakt.com", "moakt.ws",
  "mohmal.com", "mohmal.in", "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
  "mt2009.com", "mt2014.com", "mt2015.com", "mytrashmail.com", "nada.email", "nervmich.net",
  "nervtmich.net", "netmails.com", "netmails.net", "neverbox.com", "no-spam.ws", "nobulk.com",
  "noclickemail.com", "nogmailspam.info", "nomail.xl.cx", "nomail2me.com", "nospam.ze.tc",
  "notmailinator.com", "nowmymail.com", "objectmail.com", "objectmail.de", "obobbo.com",
  "onewaymail.com", "ovpn.to", "owlpic.com", "pookmail.com", "proxymail.eu", "rcpt.at",
  "reallymymail.com", "recode.me", "recursor.net", "regbypass.com", "rhyta.com", "rmqkr.net",
  "safe-mail.net", "selfdestructingmail.com", "sendspamhere.com", "sharklasers.com",
  "shieldedmail.com", "shiftmail.com", "smashmail.de", "smellfear.com", "snakemail.com",
  "sneakemail.com", "sofort-mail.de", "sogetthis.com", "soodonims.com", "spam.la", "spam4.me",
  "spamavert.com", "spambog.com", "spambog.de", "spambog.ru", "spambox.us", "spamday.com",
  "spamfree24.de", "spamfree24.org", "spamgourmet.com", "spamherelots.com",
  "spamhereplease.com", "spamhole.com", "spaml.com", "spaml.de", "spamthis.co.uk",
  "speed.1s.fr", "stop-my-spam.com", "supergreatmail.com", "superrito.com", "tagyourself.com",
  "teleg.eu", "teleworm.com", "teleworm.us", "temp-mail.io", "temp-mail.org", "temp-mail.ru",
  "tempail.com", "tempemail.com", "tempemail.net", "tempemailco.com", "tempinbox.com",
  "tempmail.com", "tempmail.email", "tempmail.net", "tempmailaddress.com", "tempmailer.com",
  "tempmailer.de", "tempmailo.com", "tempr.email", "tempymail.com", "thankyou2010.com",
  "thisisnotmyrealemail.com", "throwam.com", "throwawaymail.com", "tmail.ws", "tmailinator.com",
  "tmails.net", "tmpmail.net", "tmpmail.org", "tradermail.info", "trash-mail.com",
  "trash-mail.de", "trash2009.com", "trash2010.com", "trash2011.com", "trashmail.com",
  "trashmail.de", "trashmail.net", "trashmail.org", "trbvm.com", "trialmail.de", "twinmail.de",
  "txcct.com", "venompen.com", "veryrealemail.com", "vjuum.com", "vomoto.com", "wegwerfmail.de",
  "wegwerfmail.net", "wegwerfmail.org", "wh4f.org", "willhackforfood.biz",
  "willselfdestruct.com", "wuzup.net", "wuzupmail.net", "wwjmp.com", "xagloo.com", "xojxe.com",
  "yepmail.net", "yopmail.com", "yopmail.fr", "yopmail.gq", "yopmail.net", "zehnminuten.de",
  "zehnminutenmail.de", "zoemail.com", "zoemail.net", "zoemail.org",
]);
