import { cp, mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
export const projectRoot = resolve(scriptDirectory, "..");
export const defaultOutputDirectory = join(projectRoot, "dist-pages");
const subdivisionRoot = join(projectRoot, "games", "subdivision");

export function normalizeBackendUrl(value) {
  const candidate = String(value || "").trim();
  if (!candidate) throw new Error("PUBLIC_BACKEND_URL is required (for example https://orbit-ops.onrender.com).");
  let url;
  try {
    url = new URL(candidate);
  } catch {
    throw new Error("PUBLIC_BACKEND_URL must be a valid absolute URL.");
  }
  if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.search || url.hash) {
    throw new Error("PUBLIC_BACKEND_URL must be a plain HTTP(S) origin without credentials, query, or fragment.");
  }
  if (url.pathname !== "/") throw new Error("PUBLIC_BACKEND_URL must not contain a path.");
  return url.origin;
}

export function subdivisionSocketUrl(backendUrl) {
  const url = new URL(normalizeBackendUrl(backendUrl));
  url.protocol = url.protocol === "https:" ? "wss:" : "ws:";
  url.pathname = "/tips/ws";
  return url.href;
}

export function prefixSubdivisionDocument(source, fileName) {
  let text = String(source);
  if (fileName === "maps.js") return text.replaceAll("/assets/", "/tips/assets/");
  if (!["index.html", "legal.html"].includes(fileName)) return text;
  for (const assetPath of [
    "/assets/",
    "/orbit-ops-subdivision-badge-simple.png",
    "/orbit-ops-subdivision-logo-simple.png",
    "/dust2-minimap.png",
    "/client-config.js",
    "/maps.js",
    "/core.js",
    "/sw.js"
  ]) {
    text = text.replaceAll(assetPath, `/tips${assetPath}`);
  }
  text = text.replaceAll("/legal", "/tips/legal");
  if (fileName === "legal.html") text = text.replaceAll('href="/"', 'href="/tips/"');
  return text;
}

export function orbitClientConfig(backendUrl) {
  return `// Generated by scripts/buildCloudflarePages.mjs.\n` +
    `window.ORBIT_OPS_CLIENT_CONFIG = Object.freeze({\n` +
    `  backendUrl: ${JSON.stringify(normalizeBackendUrl(backendUrl))},\n` +
    `  subdivisionUrl: "/tips/"\n` +
    `});\n`;
}

export function subdivisionClientConfig(backendUrl) {
  return `// Generated by scripts/buildCloudflarePages.mjs.\n` +
    `window.JIMS_CLIENT_CONFIG = Object.freeze({\n` +
    `  multiplayerUrl: ${JSON.stringify(subdivisionSocketUrl(backendUrl))},\n` +
    `  apiKey: "",\n` +
    `  serviceWorkerEnabled: true,\n` +
    `  orbitReturnUrl: "/"\n` +
    `});\n`;
}

export function cloudflareHeaders(backendUrl) {
  const backend = new URL(normalizeBackendUrl(backendUrl));
  const socketOrigin = `${backend.protocol === "https:" ? "wss:" : "ws:"}//${backend.host}`;
  return `/*\n` +
    `  X-Content-Type-Options: nosniff\n` +
    `  Referrer-Policy: same-origin\n` +
    `  Permissions-Policy: camera=(), microphone=(), geolocation=()\n` +
    `\n` +
    `/\n` +
    `  Cache-Control: no-cache\n` +
    `  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self' ${backend.origin} ${socketOrigin}; font-src 'self' data:; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'\n` +
    `\n` +
    `/index.html\n` +
    `  Cache-Control: no-cache\n` +
    `  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self' ${backend.origin} ${socketOrigin}; font-src 'self' data:; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'\n` +
    `\n` +
    `/src/*\n` +
    `  Cache-Control: no-cache\n` +
    `\n` +
    `/client-config.js\n` +
    `  Cache-Control: no-store\n` +
    `\n` +
    `/assets/*\n` +
    `  Cache-Control: public, max-age=86400, stale-while-revalidate=604800\n` +
    `\n` +
    `/vendor/*\n` +
    `  Cache-Control: public, max-age=86400, stale-while-revalidate=604800\n` +
    `\n` +
    `/socket.io/*\n` +
    `  Cache-Control: public, max-age=86400, stale-while-revalidate=604800\n` +
    `\n` +
    `/tips/*\n` +
    `  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self' ${backend.origin} ${socketOrigin} https://cdn.jsdelivr.net; font-src 'self' data:; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'\n` +
    `\n` +
    `/tips/index.html\n` +
    `  Cache-Control: no-cache\n` +
    `\n` +
    `/tips/legal.html\n` +
    `  Cache-Control: no-cache\n` +
    `\n` +
    `/tips/*.js\n` +
    `  Cache-Control: no-store\n` +
    `\n` +
    `/tips/assets/*\n` +
    `  Cache-Control: public, max-age=86400, stale-while-revalidate=604800\n`;
}

function assertSafeOutput(outputDirectory) {
  const output = resolve(outputDirectory);
  const relativePath = relative(projectRoot, output);
  if (!relativePath || relativePath.startsWith("..") || relativePath.includes(`${sep}..${sep}`)) {
    throw new Error("CLOUDFLARE_PAGES_OUTPUT must be a dedicated directory inside this repository.");
  }
  if (!relativePath.startsWith("dist-")) {
    throw new Error("CLOUDFLARE_PAGES_OUTPUT must use a dist-* directory so cleanup cannot target source files.");
  }
  return output;
}

async function copyTree(source, destination) {
  await cp(source, destination, {
    recursive: true,
    filter: (entry) => !entry.endsWith(`${sep}.DS_Store`)
  });
}

async function copySubdivision(stagingDirectory, backendUrl, buildId) {
  const destination = join(stagingDirectory, "tips");
  await mkdir(destination, { recursive: true });
  await copyTree(join(subdivisionRoot, "assets"), join(destination, "assets"));
  for (const fileName of [
    "orbit-ops-subdivision-badge-simple.png",
    "orbit-ops-subdivision-logo-simple.png",
    "dust2-minimap.png",
    "core.js"
  ]) {
    await cp(join(subdivisionRoot, fileName), join(destination, fileName));
  }
  for (const fileName of ["index.html", "legal.html", "maps.js"]) {
    const source = await readFile(join(subdivisionRoot, fileName), "utf8");
    await writeFile(join(destination, fileName), prefixSubdivisionDocument(source, fileName));
  }
  const worker = (await readFile(join(subdivisionRoot, "sw.js"), "utf8"))
    .replace("james-garden-care-assets-v1", `orbit-ops-subdivision-pages-assets-${buildId}`)
    .replace(
      "name.startsWith('jims-game-assets-') || name.startsWith('james-garden-care-assets-')",
      "name.startsWith('jims-game-assets-') || name.startsWith('james-garden-care-assets-') || name.startsWith('orbit-ops-subdivision-pages-assets-')"
    )
    .replace("url.pathname.startsWith('/assets/')", "url.pathname.startsWith('/tips/assets/')");
  await writeFile(join(destination, "sw.js"), worker);
  await writeFile(join(destination, "client-config.js"), subdivisionClientConfig(backendUrl));
}

export async function buildCloudflarePages({
  backendUrl = process.env.PUBLIC_BACKEND_URL,
  outputDirectory = process.env.CLOUDFLARE_PAGES_OUTPUT || defaultOutputDirectory,
  buildId = String(process.env.CF_PAGES_COMMIT_SHA || "local").slice(0, 16).replace(/[^a-z0-9_-]/giu, "") || "local"
} = {}) {
  const backend = normalizeBackendUrl(backendUrl);
  const output = assertSafeOutput(outputDirectory);
  const staging = `${output}.staging-${process.pid}`;
  await rm(staging, { recursive: true, force: true });
  await mkdir(staging, { recursive: true });
  try {
    await copyTree(join(projectRoot, "public"), staging);
    await mkdir(join(staging, "vendor", "phaser", "dist"), { recursive: true });
    await cp(join(projectRoot, "node_modules", "phaser", "dist", "phaser.min.js"), join(staging, "vendor", "phaser", "dist", "phaser.min.js"));
    await mkdir(join(staging, "socket.io"), { recursive: true });
    await cp(join(projectRoot, "node_modules", "socket.io", "client-dist", "socket.io.min.js"), join(staging, "socket.io", "socket.io.js"));
    await writeFile(join(staging, "client-config.js"), orbitClientConfig(backend));
    await copySubdivision(staging, backend, buildId);
    await writeFile(join(staging, "_headers"), cloudflareHeaders(backend));
    await writeFile(join(staging, "_redirects"), "/tips /tips/ 301\n/tips/legal /tips/legal.html 200\n");
    await rm(output, { recursive: true, force: true });
    await rename(staging, output);
  } catch (error) {
    await rm(staging, { recursive: true, force: true });
    throw error;
  }
  const details = await stat(output);
  if (!details.isDirectory()) throw new Error("Cloudflare output was not created as a directory.");
  return { backendUrl: backend, outputDirectory: output };
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (import.meta.url === invokedPath) {
  buildCloudflarePages()
    .then(({ backendUrl, outputDirectory }) => {
      console.log(`Cloudflare Pages bundle ready: ${relative(projectRoot, outputDirectory)}`);
      console.log(`Public multiplayer backend: ${backendUrl}`);
    })
    .catch((error) => {
      console.error(`Cloudflare Pages build failed: ${error.message}`);
      process.exitCode = 1;
    });
}
