import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const assetRoot = join(root, "public", "assets", "art");

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(path));
    else if (extname(entry.name).toLowerCase() === ".png") files.push(path);
  }
  return files;
}

function readPngDimensions(buffer) {
  if (buffer.toString("ascii", 1, 4) !== "PNG") throw new Error("Not a PNG file.");
  return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
}

function webPath(relativePath) {
  return `/assets/art/${relativePath.split(sep).map(encodeURIComponent).join("/")}`;
}

function intendedUse(category) {
  return ({
    "Accessories & Pets": "character customisation reference and provisional cosmetics",
    Background: "space, anomaly and menu parallax",
    "DISCUSS!": "meeting transition and discussion presentation",
    Fonts: "holographic display texture reference",
    Gui: "provisional controls, map and menu presentation",
    "Kill Stabs": "stylised elimination effect reference",
    Maps: "provisional room and environment reference",
    Players: "provisional character and hand interaction reference",
    "SHHHHH!": "role reveal transition",
    Tasks: "assignment interfaces and holographic station reference",
    Unused: "optional seasonal effect archive",
    Voting: "meeting and vote presentation"
  })[category] ?? "provisional visual reference";
}

const files = (await walk(assetRoot)).sort((a, b) => a.localeCompare(b));
const catalog = [];
for (const file of files) {
  const relativePath = relative(assetRoot, file);
  const buffer = await readFile(file);
  const dimensions = readPngDimensions(buffer);
  const [category] = relativePath.split(sep);
  catalog.push({
    key: relativePath.replace(/\.png$/iu, "").replace(/[^a-z0-9]+/giu, "-").replace(/^-|-$/gu, "").toLowerCase(),
    filename: relativePath.split(sep).at(-1),
    sourceRelativePath: relativePath.split(sep).join("/"),
    path: webPath(relativePath),
    type: "texture",
    format: "png",
    category,
    intendedUse: intendedUse(category),
    width: dimensions.width,
    height: dimensions.height,
    essential: false,
    provisional: true,
    status: "catalogued",
    replacementBoundary: "Replace through ART_CATALOG or the dedicated map/character/task adapter; game rules do not depend on this file."
  });
}

if (catalog.some((asset) => asset.category === "Logos")) throw new Error("Logo assets must not be included.");

const generatedHeader = "// Generated by scripts/generateAssetCatalog.mjs. Do not edit by hand.\n";
await writeFile(join(root, "public", "src", "artCatalog.js"), `${generatedHeader}export const ART_CATALOG = Object.freeze(${JSON.stringify(catalog, null, 2)});\n`, "utf8");
await writeFile(join(root, "docs", "asset-inventory.json"), `${JSON.stringify({ generatedAt: new Date().toISOString(), excludedCategories: ["Logos"], count: catalog.length, assets: catalog }, null, 2)}\n`, "utf8");
console.log(`Catalogued ${catalog.length} non-logo Orbit Ops art assets.`);
