-- ===========================================================================
-- Realign stored case drops with the calibrated skin catalogue.
--
-- Run the steps IN ORDER. Steps 1-3 change nothing. Step 5 is the write.
--
-- The six cases authored by the original dev team are excluded everywhere:
--   wearhouse, tradie, mulch, lawn_care, gardener, diamond_strong
-- Do not remove that filter.
--
-- Generated from skins.js. Not run against a live database.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- STEP 1 - snapshot you can roll back to. Safe.
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS custom_cases_backup_rarity;
CREATE TABLE custom_cases_backup_rarity AS SELECT * FROM custom_cases;


-- ---------------------------------------------------------------------------
-- STEP 2 - stage the calibrated catalogue. Safe. Dropped again in step 7.
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS catalog_rarity;
CREATE TABLE catalog_rarity (item_id text PRIMARY KEY, rarity text NOT NULL);

INSERT INTO catalog_rarity (item_id, rarity) VALUES
  ('ak47_ice_coaled', 'epic'),
  ('ak47_nightwish', 'legendary'),
  ('ak47_anubis', 'epic'),
  ('ak47_asiimov', 'epic'),
  ('ak47_crossfade', 'common'),
  ('ak47_inheritence', 'legendary'),
  ('ak47_phantom_disruptor', 'epic'),
  ('ak47_point_disarray', 'epic'),
  ('ak47_the_empress', 'legendary'),
  ('ak47_wild_lotus', 'legendary'),
  ('awp_asiimov', 'epic'),
  ('awp_crakow', 'epic'),
  ('awp_bingle', 'legendary'),
  ('awp_desert_hydra', 'legendary'),
  ('awp_dragon_lore', 'legendary'),
  ('awp_gungnir', 'legendary'),
  ('awp_jog', 'epic'),
  ('awp_neo_noir', 'epic'),
  ('awp_oni_taiji', 'legendary'),
  ('awp_the_prince', 'legendary'),
  ('awp_wildfire', 'legendary'),
  ('dual_berettas_carbon_service', 'common'),
  ('dual_berettas_urban_signal', 'common'),
  ('dual_berettas_desert_pulse', 'rare'),
  ('dual_berettas_arctic_vector', 'rare'),
  ('dual_berettas_oxide_bloom', 'rare'),
  ('dual_berettas_neon_crossfire', 'epic'),
  ('dual_berettas_abyssal_bloom', 'epic'),
  ('dual_berettas_prism_static', 'epic'),
  ('dual_berettas_helios_fracture', 'legendary'),
  ('dual_berettas_imperial_voltage', 'legendary'),
  ('awp_sovereign_flame', 'legendary'),
  ('famas_underground', 'epic'),
  ('shield_aurora_aegis', 'legendary'),
  ('shield_crimson_bulwark', 'rare'),
  ('breacher_ember_entry', 'rare'),
  ('breacher_night_entry', 'common'),
  ('rpg_orbital_energy', 'rare'),
  ('rpg_launch_control', 'common'),
  ('rpg_franklin', 'rare'),
  ('rpg_case_hardened', 'legendary'),
  ('rpg_fade', 'epic'),
  ('rpg_scorched', 'common'),
  ('rpg_royal_camo', 'common'),
  ('rpg_blue_steel', 'common'),
  ('rpg_snake_camo', 'common'),
  ('rpg_ultraviolet_swirl', 'common'),
  ('breacher_case_hardened', 'legendary'),
  ('breacher_graphite_tech', 'common'),
  ('breacher_boreal_forest', 'common'),
  ('breacher_fade', 'epic'),
  ('breacher_scales', 'common'),
  ('breacher_arid_camo', 'common'),
  ('breacher_crimson_web', 'common'),
  ('breacher_dual_energy', 'rare'),
  ('shield_blue_steel', 'common'),
  ('shield_royal_camo', 'common'),
  ('shield_forest_ddpat', 'common'),
  ('shield_gamma_energy', 'epic'),
  ('shield_graphite_tech', 'common'),
  ('shield_pyrotechnic', 'common'),
  ('shield_ultraviolet_swirl', 'common'),
  ('shield_woodgrain', 'common'),
  ('shield_rexton', 'rare'),
  ('knife_bayonet_vanilla', 'mythic'),
  ('knife_bowie_vanilla', 'mythic'),
  ('knife_butterfly_vanilla', 'mythic'),
  ('knife_canis_vanilla', 'mythic'),
  ('knife_cord_vanilla', 'mythic'),
  ('knife_css_vanilla', 'mythic'),
  ('knife_default_ct_vanilla', 'common'),
  ('knife_default_t_vanilla', 'common'),
  ('knife_falchion_vanilla', 'mythic'),
  ('knife_flip_vanilla', 'mythic'),
  ('knife_gut_vanilla', 'mythic'),
  ('knife_karambit_vanilla', 'mythic'),
  ('knife_kukri_vanilla', 'mythic'),
  ('knife_m9_vanilla', 'mythic'),
  ('knife_navaja_vanilla', 'mythic'),
  ('knife_outdoor_vanilla', 'mythic'),
  ('knife_skeleton_vanilla', 'mythic'),
  ('knife_stiletto_vanilla', 'mythic'),
  ('knife_tactical_vanilla', 'mythic'),
  ('knife_talon_vanilla', 'mythic'),
  ('knife_ursus_vanilla', 'mythic'),
  ('knife_karambit_vortex_fang', 'mythic'),
  ('knife_bowie_solar_reaver', 'mythic'),
  ('ak47_arid_camo', 'common'),
  ('ak47_case_hardened', 'legendary'),
  ('ak47_forest_ddpat', 'common'),
  ('ak47_franklin', 'rare'),
  ('ak47_night_stripe', 'common'),
  ('ak47_olive_drab', 'common'),
  ('ak47_pyrotechnic', 'common'),
  ('ak47_royal_camo', 'common'),
  ('ak47_ultraviolet_swirl', 'common'),
  ('ak47_urban_ddpat', 'common'),
  ('ak47_urban_masked', 'common'),
  ('ak47_woodgrain', 'common'),
  ('awp_arid_camo', 'common'),
  ('awp_blue_steel', 'common'),
  ('awp_forest_ddpat', 'common'),
  ('awp_franklin', 'rare'),
  ('awp_ice_coaled', 'epic'),
  ('awp_olive_drab', 'common'),
  ('awp_printstream', 'legendary'),
  ('awp_pyrotechnic', 'common'),
  ('awp_royal_camo', 'common'),
  ('awp_safari_mesh', 'common'),
  ('awp_urban_ddpat', 'common'),
  ('awp_urban_masked', 'common'),
  ('awp_woodgrain', 'common'),
  ('awp_woodland_leaves', 'common'),
  ('deagle_arid_camo', 'common'),
  ('deagle_blue_steel', 'common'),
  ('deagle_boreal_forest', 'common'),
  ('deagle_code_red', 'legendary'),
  ('deagle_conspiracy', 'epic'),
  ('deagle_fennec_fox', 'epic'),
  ('deagle_firebreathing', 'legendary'),
  ('deagle_forest_ddpat', 'common'),
  ('deagle_franklin', 'rare'),
  ('deagle_graffiti_nigh', 'common'),
  ('deagle_kumicho_dragon', 'legendary'),
  ('deagle_mecha_industries', 'epic'),
  ('deagle_oxide_blaze', 'epic'),
  ('deagle_printstream', 'legendary'),
  ('deagle_pyrotechnic', 'common'),
  ('deagle_royal_camo', 'common'),
  ('deagle_safari_mesh', 'common'),
  ('deagle_scales', 'common'),
  ('deagle_starcade', 'epic'),
  ('deagle_tilted', 'epic'),
  ('deagle_trigger_discipline', 'epic'),
  ('deagle_urban_masked', 'common'),
  ('deagle_woodgrain', 'common'),
  ('deagle_woodland_leaves', 'common'),
  ('famas_afterimage', 'rare'),
  ('famas_arid_camo', 'common'),
  ('famas_bad_trip', 'legendary'),
  ('famas_blue_steel', 'common'),
  ('famas_boreal_forest', 'common'),
  ('famas_bright_water', 'common'),
  ('famas_eye_of_athena', 'epic'),
  ('famas_franklin', 'rare'),
  ('famas_graffiti_nigh', 'common'),
  ('famas_graphite_tech', 'common'),
  ('famas_mecha_industries', 'epic'),
  ('famas_meow_36', 'epic'),
  ('famas_rapid_eye_movement', 'epic'),
  ('famas_roll_cage', 'epic'),
  ('famas_royal_camo', 'common'),
  ('famas_safari_mesh', 'common'),
  ('famas_scales', 'common'),
  ('famas_scorched', 'common'),
  ('famas_survivor_z', 'epic'),
  ('famas_valence', 'epic'),
  ('famas_woodgrain', 'common'),
  ('famas_woodland_leaves', 'common'),
  ('famas_zx_spectron', 'epic'),
  ('glock_block_18', 'rare'),
  ('glock_blue_steel', 'common'),
  ('glock_boreal_forest', 'common'),
  ('glock_bright_water', 'common'),
  ('glock_bullet_queen', 'epic'),
  ('glock_fully_tuned', 'rare'),
  ('glock_gold_toof', 'rare'),
  ('glock_graffiti_nigh', 'common'),
  ('glock_graphite_tech', 'common'),
  ('glock_jaguar', 'common'),
  ('glock_mirror_mosaic', 'epic'),
  ('glock_neo_noir', 'epic'),
  ('glock_ramese_s_reach', 'legendary'),
  ('glock_sacrifice', 'rare'),
  ('glock_safari_mesh', 'common'),
  ('glock_scales', 'common'),
  ('glock_scorched', 'common'),
  ('glock_scraped_steel', 'common'),
  ('glock_shinobu', 'rare'),
  ('glock_snack_attack', 'rare'),
  ('glock_umbral_rabbit', 'rare'),
  ('glock_vogue', 'rare'),
  ('glock_wasteland_rebel', 'epic'),
  ('glock_weasel', 'rare'),
  ('glock_woodland_leaves', 'common'),
  ('knife_bayonet_arid_camo', 'mythic'),
  ('knife_bayonet_case_hardened', 'mythic'),
  ('knife_bayonet_forest_ddpat', 'mythic'),
  ('knife_bayonet_franklin', 'mythic'),
  ('knife_bayonet_jaguar', 'mythic'),
  ('knife_bayonet_knife_slaughter', 'mythic'),
  ('knife_bayonet_midnight_palm', 'mythic'),
  ('knife_bayonet_pyrotechnic', 'mythic'),
  ('knife_bayonet_safari_mesh', 'mythic'),
  ('knife_bayonet_scorched', 'mythic'),
  ('knife_bayonet_scraped_steel', 'mythic'),
  ('knife_bayonet_woodgrain', 'mythic'),
  ('knife_bowie_blue_steel', 'mythic'),
  ('knife_bowie_case_hardened', 'mythic'),
  ('knife_bowie_crimson_web', 'mythic'),
  ('knife_bowie_dual_energy', 'mythic'),
  ('knife_bowie_forest_ddpat', 'mythic'),
  ('knife_bowie_graphite_tech', 'mythic'),
  ('knife_bowie_jaguar', 'mythic'),
  ('knife_bowie_pyrotechnic', 'mythic'),
  ('knife_bowie_sunrise_dunes', 'mythic'),
  ('knife_bowie_urban_ddpat', 'mythic'),
  ('knife_bowie_urban_masked', 'mythic'),
  ('knife_bowie_woodland_leaves', 'mythic'),
  ('knife_butterfly_blue_steel', 'mythic'),
  ('knife_butterfly_control_pane', 'mythic'),
  ('knife_butterfly_forest_ddpat', 'mythic'),
  ('knife_butterfly_gamma_energy', 'mythic'),
  ('knife_butterfly_knife_slaughter', 'mythic'),
  ('knife_butterfly_olive_drab', 'mythic'),
  ('knife_butterfly_pyrotechnic', 'mythic'),
  ('knife_butterfly_royal_camo', 'mythic'),
  ('knife_butterfly_scorched', 'mythic'),
  ('knife_butterfly_scraped_steel', 'mythic'),
  ('knife_butterfly_sunrise_dunes', 'mythic'),
  ('knife_butterfly_urban_ddpat', 'mythic'),
  ('knife_classic_blue_steel', 'mythic'),
  ('knife_classic_boreal_forest', 'mythic'),
  ('knife_classic_franklin', 'mythic'),
  ('knife_classic_gamma_energy', 'mythic'),
  ('knife_classic_graphite_tech', 'mythic'),
  ('knife_classic_midnight_palm', 'mythic'),
  ('knife_classic_pyrotechnic', 'mythic'),
  ('knife_classic_safari_mesh', 'mythic'),
  ('knife_classic_sunrise_dunes', 'mythic'),
  ('knife_classic_urban_ddpat', 'mythic'),
  ('knife_classic_woodgrain', 'mythic'),
  ('knife_classic_woodland_leaves', 'mythic'),
  ('knife_default_arid_camo', 'mythic'),
  ('knife_default_blue_steel', 'mythic'),
  ('knife_default_boreal_forest', 'mythic'),
  ('knife_default_control_pane', 'mythic'),
  ('knife_default_fade', 'mythic'),
  ('knife_default_midnight_palm', 'mythic'),
  ('knife_default_pyrotechnic', 'mythic'),
  ('knife_default_scorched', 'mythic'),
  ('knife_default_snake_camo', 'mythic'),
  ('knife_default_ultraviolet_swirl', 'mythic'),
  ('knife_default_urban_ddpat', 'mythic'),
  ('knife_default_woodgrain', 'mythic'),
  ('knife_falchion_arid_camo', 'mythic'),
  ('knife_falchion_boreal_forest', 'mythic'),
  ('knife_falchion_case_hardened', 'mythic'),
  ('knife_falchion_dual_energy', 'mythic'),
  ('knife_falchion_graffiti_nigh', 'mythic'),
  ('knife_falchion_graphite_tech', 'mythic'),
  ('knife_falchion_midnight_palm', 'mythic'),
  ('knife_falchion_night_stripe', 'mythic'),
  ('knife_falchion_scales', 'mythic'),
  ('knife_falchion_scorched', 'mythic'),
  ('knife_falchion_scraped_steel', 'mythic'),
  ('knife_falchion_woodland_leaves', 'mythic'),
  ('knife_flip_boreal_forest', 'mythic'),
  ('knife_flip_crimson_web', 'mythic'),
  ('knife_flip_franklin', 'mythic'),
  ('knife_flip_gamma_energy', 'mythic'),
  ('knife_flip_graffiti_nigh', 'mythic'),
  ('knife_flip_jaguar', 'mythic'),
  ('knife_flip_midnight_palm', 'mythic'),
  ('knife_flip_night_stripe', 'mythic'),
  ('knife_flip_olive_drab', 'mythic'),
  ('knife_flip_scales', 'mythic'),
  ('knife_flip_sunrise_dunes', 'mythic'),
  ('knife_flip_ultraviolet_swirl', 'mythic'),
  ('knife_gut_arid_camo', 'mythic'),
  ('knife_gut_blue_steel', 'mythic'),
  ('knife_gut_boreal_forest', 'mythic'),
  ('knife_gut_bright_water', 'mythic'),
  ('knife_gut_case_hardened', 'mythic'),
  ('knife_gut_dual_energy', 'mythic'),
  ('knife_gut_franklin', 'mythic'),
  ('knife_gut_graffiti_nigh', 'mythic'),
  ('knife_gut_pyrotechnic', 'mythic'),
  ('knife_gut_safari_mesh', 'mythic'),
  ('knife_gut_sunrise_dunes', 'mythic'),
  ('knife_gut_ultraviolet_swirl', 'mythic'),
  ('knife_huntsman_boreal_forest', 'mythic'),
  ('knife_huntsman_control_pane', 'mythic'),
  ('knife_huntsman_crimson_web', 'mythic'),
  ('knife_huntsman_franklin', 'mythic'),
  ('knife_huntsman_graphite_tech', 'mythic'),
  ('knife_huntsman_knife_slaughter', 'mythic'),
  ('knife_huntsman_olive_drab', 'mythic'),
  ('knife_huntsman_pyrotechnic', 'mythic'),
  ('knife_huntsman_scales', 'mythic'),
  ('knife_huntsman_scorched', 'mythic'),
  ('knife_huntsman_ultraviolet_swirl', 'mythic'),
  ('knife_huntsman_urban_masked', 'mythic'),
  ('knife_karambit_bright_water', 'mythic'),
  ('knife_karambit_case_hardened', 'mythic'),
  ('knife_karambit_control_pane', 'mythic'),
  ('knife_karambit_crimson_web', 'mythic'),
  ('knife_karambit_forest_ddpat', 'mythic'),
  ('knife_karambit_franklin', 'mythic'),
  ('knife_karambit_graphite_tech', 'mythic'),
  ('knife_karambit_knife_slaughter', 'mythic'),
  ('knife_karambit_midnight_palm', 'mythic'),
  ('knife_karambit_scraped_steel', 'mythic'),
  ('knife_karambit_snake_camo', 'mythic'),
  ('knife_karambit_sunrise_dunes', 'mythic'),
  ('knife_kukri_dual_energy', 'mythic'),
  ('knife_kukri_fade', 'mythic'),
  ('knife_kukri_forest_ddpat', 'mythic'),
  ('knife_kukri_franklin', 'mythic'),
  ('knife_kukri_midnight_palm', 'mythic'),
  ('knife_kukri_night_stripe', 'mythic'),
  ('knife_kukri_olive_drab', 'mythic'),
  ('knife_kukri_pyrotechnic', 'mythic'),
  ('knife_kukri_royal_camo', 'mythic'),
  ('knife_kukri_sunrise_dunes', 'mythic'),
  ('knife_kukri_ultraviolet_swirl', 'mythic'),
  ('knife_kukri_urban_ddpat', 'mythic'),
  ('knife_m9bayonet_blue_steel', 'mythic'),
  ('knife_m9bayonet_case_hardened', 'mythic'),
  ('knife_m9bayonet_crimson_web', 'mythic'),
  ('knife_m9bayonet_forest_ddpat', 'mythic'),
  ('knife_m9bayonet_graffiti_nigh', 'mythic'),
  ('knife_m9bayonet_knife_slaughter', 'mythic'),
  ('knife_m9bayonet_night_stripe', 'mythic'),
  ('knife_m9bayonet_royal_camo', 'mythic'),
  ('knife_m9bayonet_scales', 'mythic'),
  ('knife_m9bayonet_scorched', 'mythic'),
  ('knife_m9bayonet_scraped_steel', 'mythic'),
  ('knife_m9bayonet_sunrise_dunes', 'mythic'),
  ('knife_navaja_arid_camo', 'mythic'),
  ('knife_navaja_boreal_forest', 'mythic'),
  ('knife_navaja_control_pane', 'mythic'),
  ('knife_navaja_crimson_web', 'mythic'),
  ('knife_navaja_forest_ddpat', 'mythic'),
  ('knife_navaja_olive_drab', 'mythic'),
  ('knife_navaja_pyrotechnic', 'mythic'),
  ('knife_navaja_safari_mesh', 'mythic'),
  ('knife_navaja_scorched', 'mythic'),
  ('knife_navaja_snake_camo', 'mythic'),
  ('knife_navaja_ultraviolet_swirl', 'mythic'),
  ('knife_navaja_urban_ddpat', 'mythic'),
  ('knife_nomad_arid_camo', 'mythic'),
  ('knife_nomad_boreal_forest', 'mythic'),
  ('knife_nomad_bright_water', 'mythic'),
  ('knife_nomad_forest_ddpat', 'mythic'),
  ('knife_nomad_graphite_tech', 'mythic'),
  ('knife_nomad_jaguar', 'mythic'),
  ('knife_nomad_knife_slaughter', 'mythic'),
  ('knife_nomad_night_stripe', 'mythic'),
  ('knife_nomad_pyrotechnic', 'mythic'),
  ('knife_nomad_scales', 'mythic'),
  ('knife_nomad_scraped_steel', 'mythic'),
  ('knife_nomad_ultraviolet_swirl', 'mythic'),
  ('knife_paracord_case_hardened', 'mythic'),
  ('knife_paracord_control_pane', 'mythic'),
  ('knife_paracord_crimson_web', 'mythic'),
  ('knife_paracord_dual_energy', 'mythic'),
  ('knife_paracord_fade', 'mythic'),
  ('knife_paracord_knife_slaughter', 'mythic'),
  ('knife_paracord_midnight_palm', 'mythic'),
  ('knife_paracord_pyrotechnic', 'mythic'),
  ('knife_paracord_royal_camo', 'mythic'),
  ('knife_paracord_scraped_steel', 'mythic'),
  ('knife_paracord_sunrise_dunes', 'mythic'),
  ('knife_paracord_woodgrain', 'mythic'),
  ('knife_skeleton_arid_camo', 'mythic'),
  ('knife_skeleton_blue_steel', 'mythic'),
  ('knife_skeleton_boreal_forest', 'mythic'),
  ('knife_skeleton_bright_water', 'mythic'),
  ('knife_skeleton_crimson_web', 'mythic'),
  ('knife_skeleton_fade', 'mythic'),
  ('knife_skeleton_forest_ddpat', 'mythic'),
  ('knife_skeleton_knife_slaughter', 'mythic'),
  ('knife_skeleton_olive_drab', 'mythic'),
  ('knife_skeleton_pyrotechnic', 'mythic'),
  ('knife_skeleton_scales', 'mythic'),
  ('knife_skeleton_sunrise_dunes', 'mythic'),
  ('knife_stiletto_blue_steel', 'mythic'),
  ('knife_stiletto_boreal_forest', 'mythic'),
  ('knife_stiletto_crimson_web', 'mythic'),
  ('knife_stiletto_dual_energy', 'mythic'),
  ('knife_stiletto_fade', 'mythic'),
  ('knife_stiletto_graffiti_nigh', 'mythic'),
  ('knife_stiletto_jaguar', 'mythic'),
  ('knife_stiletto_night_stripe', 'mythic'),
  ('knife_stiletto_olive_drab', 'mythic'),
  ('knife_stiletto_scraped_steel', 'mythic'),
  ('knife_stiletto_snake_camo', 'mythic'),
  ('knife_stiletto_ultraviolet_swirl', 'mythic'),
  ('knife_survival_blue_steel', 'mythic'),
  ('knife_survival_boreal_forest', 'mythic'),
  ('knife_survival_case_hardened', 'mythic'),
  ('knife_survival_crimson_web', 'mythic'),
  ('knife_survival_jaguar', 'mythic'),
  ('knife_survival_knife_slaughter', 'mythic'),
  ('knife_survival_night_stripe', 'mythic'),
  ('knife_survival_safari_mesh', 'mythic'),
  ('knife_survival_scraped_steel', 'mythic'),
  ('knife_survival_urban_ddpat', 'mythic'),
  ('knife_survival_woodgrain', 'mythic'),
  ('knife_survival_woodland_leaves', 'mythic'),
  ('knife_talon_blue_steel', 'mythic'),
  ('knife_talon_fade', 'mythic'),
  ('knife_talon_forest_ddpat', 'mythic'),
  ('knife_talon_franklin', 'mythic'),
  ('knife_talon_graphite_tech', 'mythic'),
  ('knife_talon_night_stripe', 'mythic'),
  ('knife_talon_scorched', 'mythic'),
  ('knife_talon_scraped_steel', 'mythic'),
  ('knife_talon_snake_camo', 'mythic'),
  ('knife_talon_urban_ddpat', 'mythic'),
  ('knife_talon_urban_masked', 'mythic'),
  ('knife_talon_woodland_leaves', 'mythic'),
  ('knife_ursus_blue_steel', 'mythic'),
  ('knife_ursus_boreal_forest', 'mythic'),
  ('knife_ursus_dual_energy', 'mythic'),
  ('knife_ursus_fade', 'mythic'),
  ('knife_ursus_franklin', 'mythic'),
  ('knife_ursus_graffiti_nigh', 'mythic'),
  ('knife_ursus_safari_mesh', 'mythic'),
  ('knife_ursus_scales', 'mythic'),
  ('knife_ursus_scorched', 'mythic'),
  ('knife_ursus_urban_ddpat', 'mythic'),
  ('knife_ursus_urban_masked', 'mythic'),
  ('knife_ursus_woodland_leaves', 'mythic'),
  ('mac10_allure', 'rare'),
  ('mac10_boreal_forest', 'common'),
  ('mac10_bright_water', 'common'),
  ('mac10_cat_fight', 'legendary'),
  ('mac10_control_pane', 'common'),
  ('mac10_curse', 'rare'),
  ('mac10_derailment', 'rare'),
  ('mac10_graffiti_nigh', 'common'),
  ('mac10_graphite_tech', 'common'),
  ('mac10_jaguar', 'common'),
  ('mac10_monkeyflage', 'rare'),
  ('mac10_neon_rider', 'epic'),
  ('mac10_propaganda', 'rare'),
  ('mac10_rangeen', 'epic'),
  ('mac10_saiba_oni', 'rare'),
  ('mac10_sakkaku', 'rare'),
  ('mac10_scales', 'common'),
  ('mac10_scorched', 'common'),
  ('mac10_scraped_steel', 'common'),
  ('mac10_snake_camo', 'common'),
  ('mac10_stalker', 'legendary'),
  ('mac10_toybox', 'rare'),
  ('nova_antique', 'rare'),
  ('nova_bloomstick', 'rare'),
  ('nova_bright_water', 'common'),
  ('nova_control_pane', 'common'),
  ('nova_crimson_web', 'common'),
  ('nova_dark_sigil', 'rare'),
  ('nova_graphite_tech', 'common'),
  ('nova_hyper_beast', 'epic'),
  ('nova_jaguar', 'common'),
  ('nova_koi', 'rare'),
  ('nova_midnight_palm', 'common'),
  ('nova_ocular', 'epic'),
  ('nova_rising_sun', 'legendary'),
  ('nova_scorched', 'common'),
  ('nova_scraped_steel', 'common'),
  ('nova_snake_camo', 'common'),
  ('nova_sunrise_dunes', 'common'),
  ('nova_toy_soldier', 'rare'),
  ('nova_wood_fired', 'rare'),
  ('nova_wurst_holle', 'rare'),
  ('p90_asiimov', 'epic'),
  ('p90_chopper', 'rare'),
  ('p90_control_pane', 'common'),
  ('p90_crimson_web', 'common'),
  ('p90_deathgaze', 'legendary'),
  ('p90_emerald_dragon', 'epic'),
  ('p90_freight', 'rare'),
  ('p90_jaguar', 'common'),
  ('p90_midnight_palm', 'common'),
  ('p90_neoqueen', 'epic'),
  ('p90_night_stripe', 'common'),
  ('p90_nostalgia', 'rare'),
  ('p90_randy_rush', 'rare'),
  ('p90_run_and_hide', 'rare'),
  ('p90_scraped_steel', 'common'),
  ('p90_snake_camo', 'common'),
  ('p90_sunrise_dunes', 'common'),
  ('p90_trigon', 'rare'),
  ('p90_ultraviolet_swirl', 'common'),
  ('p90_wave_breaker', 'rare'),
  ('ssg08_big_iron', 'epic'),
  ('ssg08_blood_in_the_water', 'legendary'),
  ('ssg08_bloodshot', 'epic'),
  ('ssg08_control_pane', 'common'),
  ('ssg08_crimson_web', 'common'),
  ('ssg08_death_strike', 'epic'),
  ('ssg08_death_s_head', 'epic'),
  ('ssg08_dragonfire', 'legendary'),
  ('ssg08_fever_dream', 'rare'),
  ('ssg08_ghost_crusader', 'epic'),
  ('ssg08_hand_brake', 'epic'),
  ('ssg08_midnight_palm', 'common'),
  ('ssg08_night_stripe', 'common'),
  ('ssg08_olive_drab', 'common'),
  ('ssg08_snake_camo', 'common'),
  ('ssg08_sunrise_dunes', 'common'),
  ('ssg08_turbo_peek', 'epic'),
  ('ssg08_ultraviolet_swirl', 'common'),
  ('ssg08_urban_ddpat', 'common'),
  ('xm1014_black_tie', 'rare'),
  ('xm1014_crimson_web', 'common'),
  ('xm1014_forest_ddpat', 'common'),
  ('xm1014_heaven_guard', 'rare'),
  ('xm1014_incinegator', 'rare'),
  ('xm1014_irezumi', 'legendary'),
  ('xm1014_midnight_palm', 'common'),
  ('xm1014_monster_melt', 'rare'),
  ('xm1014_night_stripe', 'common'),
  ('xm1014_olive_drab', 'common'),
  ('xm1014_oxide_blaze', 'epic'),
  ('xm1014_pyrotechnic', 'common'),
  ('xm1014_red_leather', 'rare'),
  ('xm1014_run_run_run', 'rare'),
  ('xm1014_sunrise_dunes', 'common'),
  ('xm1014_tranquility', 'rare'),
  ('xm1014_ultraviolet_swirl', 'common'),
  ('xm1014_urban_ddpat', 'common'),
  ('xm1014_urban_masked', 'common'),
  ('xm1014_watchdog', 'epic');


-- ---------------------------------------------------------------------------
-- STEP 3 - preview. Safe. Every drop that would change, and every case
-- summarised. READ THIS BEFORE STEP 5.
--
-- If a case deliberately nudged a tier, it shows up here and step 5 will
-- flatten it. That is the one thing worth checking by eye.
-- ---------------------------------------------------------------------------
SELECT c.id                   AS case_id,
       e.value ->> 'itemId'   AS item_id,
       e.value ->> 'rarity'   AS stored_rarity,
       cat.rarity             AS new_rarity
  FROM custom_cases c
  CROSS JOIN LATERAL jsonb_array_elements(c.items_json) AS e(value)
  JOIN catalog_rarity cat ON cat.item_id = e.value ->> 'itemId'
 WHERE c.id NOT IN ('wearhouse','tradie','mulch','lawn_care','gardener','diamond_strong')
   AND lower(e.value ->> 'rarity') IS DISTINCT FROM cat.rarity
 ORDER BY c.id, item_id;

SELECT c.id AS case_id,
       count(*) AS drops,
       count(*) FILTER (WHERE lower(e.value ->> 'rarity') IS DISTINCT FROM cat.rarity) AS would_change
  FROM custom_cases c
  CROSS JOIN LATERAL jsonb_array_elements(c.items_json) AS e(value)
  JOIN catalog_rarity cat ON cat.item_id = e.value ->> 'itemId'
 WHERE c.id NOT IN ('wearhouse','tradie','mulch','lawn_care','gardener','diamond_strong')
 GROUP BY c.id
 ORDER BY would_change DESC, c.id;


-- ---------------------------------------------------------------------------
-- STEP 4 - fingerprint the six reference cases. Safe.
--
-- Run this now, keep the output, and run it again after step 7. The two must
-- be identical - that is the proof the migration did not touch the cases the
-- original dev team authored.
-- ---------------------------------------------------------------------------
SELECT c.id AS case_id,
       count(*)                                                          AS drops,
       count(*) FILTER (WHERE lower(e.value ->> 'rarity') = 'common')    AS common,
       count(*) FILTER (WHERE lower(e.value ->> 'rarity') = 'rare')      AS rare,
       count(*) FILTER (WHERE lower(e.value ->> 'rarity') = 'epic')      AS epic,
       count(*) FILTER (WHERE lower(e.value ->> 'rarity') = 'legendary') AS legendary,
       count(*) FILTER (WHERE lower(e.value ->> 'rarity') = 'mythic')    AS mythic,
       md5(string_agg(e.value ->> 'itemId' || ':' || (e.value ->> 'rarity'), ',' ORDER BY e.value ->> 'itemId')) AS fingerprint
  FROM custom_cases c
  CROSS JOIN LATERAL jsonb_array_elements(c.items_json) AS e(value)
 WHERE c.id IN ('wearhouse','tradie','mulch','lawn_care','gardener','diamond_strong')
 GROUP BY c.id
 ORDER BY c.id;


-- ---------------------------------------------------------------------------
-- STEP 5 - THE WRITE. Rewrites items_json so every drop outside the six
-- reference cases carries its catalogue tier.
--
-- Drop order is preserved (WITH ORDINALITY). A drop whose itemId is not in the
-- catalogue is left exactly as it was (LEFT JOIN + CASE).
-- ---------------------------------------------------------------------------
BEGIN;

WITH rebuilt AS (
  SELECT c.id,
         jsonb_agg(
           CASE WHEN cat.rarity IS NULL
                THEN e.value
                ELSE jsonb_set(e.value, '{rarity}', to_jsonb(cat.rarity))
           END
           ORDER BY e.ord
         ) AS items_json
    FROM custom_cases c
    CROSS JOIN LATERAL jsonb_array_elements(c.items_json) WITH ORDINALITY AS e(value, ord)
    LEFT JOIN catalog_rarity cat ON cat.item_id = e.value ->> 'itemId'
   WHERE c.id NOT IN ('wearhouse','tradie','mulch','lawn_care','gardener','diamond_strong')
   GROUP BY c.id
)
UPDATE custom_cases c
   SET items_json = r.items_json
  FROM rebuilt r
 WHERE r.id = c.id;


-- ---------------------------------------------------------------------------
-- STEP 6 - verify inside the transaction. Must return 0 rows.
-- If it does not, run ROLLBACK; instead of COMMIT;
-- ---------------------------------------------------------------------------
SELECT c.id AS case_id, e.value ->> 'itemId' AS item_id,
       e.value ->> 'rarity' AS stored_rarity, cat.rarity AS expected
  FROM custom_cases c
  CROSS JOIN LATERAL jsonb_array_elements(c.items_json) AS e(value)
  JOIN catalog_rarity cat ON cat.item_id = e.value ->> 'itemId'
 WHERE c.id NOT IN ('wearhouse','tradie','mulch','lawn_care','gardener','diamond_strong')
   AND lower(e.value ->> 'rarity') IS DISTINCT FROM cat.rarity;

COMMIT;


-- ---------------------------------------------------------------------------
-- STEP 7 - tidy up. Safe. Keep the backup table until you are happy.
-- ---------------------------------------------------------------------------
DROP TABLE catalog_rarity;


-- ---------------------------------------------------------------------------
-- ROLLBACK, if you need it after committing:
--
--   UPDATE custom_cases c
--      SET items_json = b.items_json
--     FROM custom_cases_backup_rarity b
--    WHERE b.id = c.id;
--
-- Once you are satisfied:
--   DROP TABLE custom_cases_backup_rarity;
-- ---------------------------------------------------------------------------
